<?php

namespace ShopBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.id IN (:array)')
            ->setParameter('array', $array);

        return $qb->getQuery()->getResult();
    }
}
